### PR TITLE
hexadecimal values changed to decimal for compatibility with older no…

### PR DESCRIPTION
**Pull request by alessandrosangalli**
…dejs versions

### CODE REVIEW

**Review by lenchv — APPROVED** [review]
looks legit

**Comment by alessandrosangalli** [comment]
can you publish this chance at NPM?

Em ter, 24 de mar de 2020 04:06, Volodymyr Liench <notifications@github.com>
escreveu:

**Comment by lenchv** [comment]
sure, I’ll publish it tonight

**Comment by alessandrosangalli** [comment]
Thanks

Em ter, 24 de mar de 2020 08:31, Volodymyr Liench <notifications@github.com>
escreveu:

**Comment by alessandrosangalli** [comment]
unfortunately what I did was not able to fully adapt to work on the version
of nodejs that I needed, it has some code features like the readBigUInt64BE
() function that has no alternative in old versions. You might want to
reverse the commit I gave you, since it has no practical effect. thank you
very much for your attention.

>

**Comment by lenchv** [comment]
@alessandrosangalli  you are right. I tested it only on nodejs v12. In lower versions, big numbers are not supported. Also, I found that crypto.createPrivateKey is not supported as well.

I fixed those [issues](https://github.com/lenchv/jks-js/pull/3/files) and released [a new version](https://github.com/lenchv/jks-js/releases). It should work fine on node>=8. If you have a chance please try it and let me know if something does not work. Also, do not hesitate to create an issue if you find something.

**Comment by alessandrosangalli** [comment]
Wow! I tested and this works fine. Thank you very much

Em ter., 24 de mar. de 2020 às 18:46, Volodymyr Liench <
notifications@github.com> escreveu:

**Pull request merged**
